"""Add reset_password column to User

Revision ID: 99bae9b3e98e
Revises: 8e4b0d284f41
Create Date: 2025-10-14 13:50:35.324378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bae9b3e98e'
down_revision = '8e4b0d284f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password', sa.Boolean(), nullable=True))
        batch_op.drop_column('new_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_password', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('reset_password')

    # ### end Alembic commands ###
